lb12/app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'input#index', as: 'input_index'

  get 'result', to: 'result#index', as: 'result_index'
  get 'result/ultimate', to: 'result#ultimate', defaults: { format: :xml }, as: 'ultimate'

  get 'users/create', to: 'users#regf', as: 'newbie'
  get 'users/login', to: 'users#login', as: 'login'
  get 'users/available', to: 'users#available'
  get 'users/logout', to: 'users#logout', as: 'logout'
  get 'users/lk', to: 'users#lk', as: 'lk'
  get 'users/list', to: 'users#list'
  post 'users/lk', to: 'users#update'
  post 'users/create', to: 'users#create', as: 'create'
  get 'users', to: 'users#auth', as: 'auth'
end

lb12/app/app/models/application_record.rb
# frozen_string_literal: true

# Record for Application
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

lb12/app/app/models/pair.rb
# frozen_string_literal: true

# Result pair record
class Pair < ApplicationRecord
  validates :one, uniqueness: true, presence: true, \
                  comparison: { greater_than_or_equal_to: 2, less_than: :two }
  validates :two, uniqueness: true, presence: true, \
                  comparison: { greater_than_or_equal_to: 2 }
  validates :max_valid_rn, presence: true, comparison: { greater_than_or_equal_to: :one }

  def finalized?
    finalized
  end

  before_create do
    self.finalized ||= false
  end

  after_create do
    Pair.where(one: ...one, finalized: false).update(finalized: true)
  end

  def to_a
    [one, two]
  end
end

lb12/app/app/models/user.rb
# frozen_string_literal: true

# User model
class User < ApplicationRecord
  validates :login, presence: true, uniqueness: true
  validates :password, presence: true
  validate :requirements

  def requirements
    a = [
      /^[\w@\d]+$/.match?(login),
      /^[\w@!\d]+$/.match?(password),
      /[A-Z]/ =~ password,
      /\d/ =~ password,
      /[!_@]/ =~ password,
      /\w/ =~ password
    ]
    errors.add(:id, 'HTML page mismatch') unless a.all?
  end
end

lb12/app/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

lb12/app/app/controllers/input_controller.rb
# frozen_string_literal: true

# Controller for Input
class InputController < ApplicationController
  before_action do
    reset_session if User.where(id: session[:uid]).first.nil?
    redirect_to newbie_path unless session.key?(:uid)
  end

  def index
    @u = User.where(id: session[:uid]).first
  end
end

lb12/app/app/controllers/result_controller.rb
# frozen_string_literal: true

# Controller for Result
class ResultController < ApplicationController
  before_action do
    reset_session if User.where(id: session[:uid]).first.nil?
    redirect_to newbie_path unless session.key?(:uid)
  end

  def index
    render(file: "#{Rails.root}/public/400.html", status: 400) unless params.key? :t_number
    @t_n = params[:t_number].to_i
    @num_list = ResultHelper.get_friends(@t_n)
    @xlst = (params.key? :xslt) && (params[:xslt] == 'true')
    @u = User.where(id: session[:uid]).first
  end

  def ultimate
    @pairs = Pair.all.order(one: :asc).to_a
    @u = User.where(id: session[:uid]).first
  end
end

lb12/app/app/controllers/users_controller.rb
# frozen_string_literal: true

# User controller
class UsersController < ApplicationController
  before_action do
    reset_session if session.key?(:uid) && User.where(id: session[:uid]).first.nil?
    if %i[create auth].include?(params[:action].to_sym) && !%i[login password].all? { |k| params.key? k }
      render(file: "#{Rails.root}/public/400.html", status: 400)
    elsif !session.key?(:uid) && %i[list lk].include?(params[:action].to_sym)
      redirect_to newbie_path
    elsif session.key?(:uid) && !%i[logout lk update available list].include?(params[:action].to_sym)
      redirect_to '/'
    end
  end

  def update
    User.where(id: session[:uid]).update(login: params[:login], password: params[:password])
    redirect_to lk_path
  end

  def lk
    @u = User.where(id: session[:uid]).first
  end

  def logout
    reset_session
    redirect_to '/'
  end

  def login; end

  def auth
    u = User.where(login: params[:login]).first
    return render 'auth', status: 401 unless u&.password == params[:password]

    session[:uid] = u.id
    redirect_to input_index_path
  end

  def regf; end

  def create
    pr = User.create(password: params[:password], login: params[:login])
    if pr.valid?
      session[:uid] = pr.id
      redirect_to input_index_path
    else
      head 500
    end
  end

  def available
    if !params.key?(:login)
      render(file: "#{Rails.root}/public/400.html", status: 400)
    elsif !User.where(login: params[:login]).first.nil?
      head 409
    else
      params[:login] == 'admin' ? head(409) : head(200)
    end
  end

  def list
    @u = User.where(id: session[:uid]).first
    @us = User.all
  end
end

lb12/app/app/helpers/application_helper.rb
# frozen_string_literal: true

# Helper for application
module ApplicationHelper
end

lb12/app/app/helpers/input_helper.rb
# frozen_string_literal: true

# Helper for Input
module InputHelper
  FRIENDS = [
    [220, 284],
    [1184, 1210],
    [2620, 2924],
    [5020, 5564],
    [6232, 6368],
    [10_744, 10_856],
    [12_285, 14_595],
    [17_296, 18_416],
    [63_020, 76_084],
    [66_928, 66_992],
    [67_095, 71_145],
    [69_615, 87_633],
    [79_750, 88_730]
  ].freeze
end

lb12/app/app/helpers/result_helper.rb
# frozen_string_literal: true

# Helper for Result
module ResultHelper
  # @param num [Integer]
  # @return [Boolean | Array(Integer, Integer)]
  def self.get_friends(num)
    edge = -> { Pair.where(finalized: false).first }
    (2..num).each { |x| friend?(x) } unless edge.call
    return [] unless edge.call

    edge = validate_edge(num, edge)
    res = Pair.where(finalized: true, two: ..num).order(one: :asc).to_a.map(&:to_a)
    edge.two <= num ? res.push(edge.to_a) : res
  end

  # @param num [Integer]
  # @param edge [Proc(Pair)]
  # @return [Pair]
  def self.validate_edge(num, edge)
    (edge.call.max_valid_rn..num).each do |itr|
      friend?(itr)
    end
    edge.call.update(max_valid_rn: num) if num > edge.call.max_valid_rn
    edge.call
  end

  # @param num [Integer]
  # @param m_valid [Integer]
  # @return [Boolean | Array(Integer, Integer)]
  def self.friend?(num)
    friend_num = friend_parse(num)
    friend_fr = friend_parse(friend_num) unless friend_num.zero?
    if (defined? friend_fr) && (num == friend_fr)
      friend_num, num = num, friend_num if friend_num > num
      Pair.create(one: friend_num, two: num, max_valid_rn: friend_num)
      true
    else
      false
    end
  end

  # @param num [Integer]
  # @return [Integer]
  def self.friend_parse(num)
    r = []
    (1..Math.sqrt(num).round).each do |n|
      next unless (num % n).zero?

      r.push(n)
      e = (num / n).round
      r.push(e) unless (e == num) || (e == n)
    end
    r.sum
  end
end

lb12/app/app/helpers/users_helper.rb
# frozen_string_literal: true

# Users helper
module UsersHelper
end

lb12/app/app/views/users/auth.html.erb
<h1>Вы ввели неверый пароль!</h1>

<h3><a href=<%= login_path %>>Повторить попытку</a></h3>

lb12/app/app/views/users/list.html.erb
<div><p>Вы вошли как <a href=<%= lk_path %>><%= @u.login %></a>. <a href=<%= logout_path %>>Выйти</a></p></div>

<h1>Список всех пользователей сайта:</h1>

<ul>
<% @us.each do |ur| %>
    <li><h3><%= ur.login %></h3></li>
<% end %>
</ul>

lb12/app/app/views/users/list.xml.erb
<?xml version="1.0" encoding="utf-8"?>

<% if @us.empty? %>

<empty />

<% else %>

<users>
<% @us.each do |ur| %>
    <user id="<%= ur.id %>">
        <name><%= ur.login %></name>
        <% if @u.login == 'admin' %>
            <password><%= ur.password %></password>
        <% else %>
            <password><%= "[FILTERED]" %></password>
        <% end %>
    </user>
<% end %>
</users>

<% end %>

lb12/app/app/views/users/lk.html.erb
<h1>Личный кабинет пользователя <%= @u.login %></h1>
<h3>Вернуться на <a href=<%= input_index_path %>>главную страницу</a></h3>
<h3>Посмотреть <a href='/users/list'>список</a> пользователей</h3>
<form method="POST" action="/users/lk" data-controller="update">
    <table>
        <tr>
            <td><label for="login">Логин: </login></td>
            <td colspan="2"><input type="text" name="login" id="login" required autocomplete="off" placeholder="Логин" value=<%= @u.login %>></td>
        </tr>
        <tr>
            <td colspan="2"><div hidden id="login_error" class="error" ></div></td>
        </tr>
        <tr>
            <td><label for="login">Пароль: </login></td>
            <td><input type="password" name="password" id="password" required placeholder="Пароль" autocomplete="off" value=<%= @u.password %>></td>
            <td><%= image_tag 'ce.svg', class: :pwdasset, 'data-subst' => (image_path 'oe.svg') %></td>
        </tr>
        <tr>
            <td colspan="3"><div hidden id="password_error" class="error" ></div></td>
        </tr>
        <tr>
            <td><label for="login">Подтвердите пароль: </login></td>
            <td><input type="password" name="passwordc" id="passwordc" placeholder="Подтвердите пароль" required autocomplete="off"></td>
            <td><%= image_tag 'ce.svg', class: :pwdasset, 'data-subst' => (image_path 'oe.svg') %></td>
        </tr>
        <tr>
            <td colspan="3"><div hidden id="passwordc_error" class="error" ></div></td>
        </tr>
        <tr>
            <td colspan="3"><input type="submit" value="Обновить"></td>
        </tr>
    </table>
</form>

lb12/app/app/views/users/login.html.erb
<h1>Создание нового пользователя</h1>
<h3>Для начала работы необходимо войти в уже существующий аккаунт или <a href=<%= newbie_path %>>зарегистрироваться</a></h3>


<form method="GET" action="/users" data-controller="login">
    <table>
        <tr>
            <td><label for="login">Логин: </login></td>
            <td colspan="2"><input type="text" name="login" id="login" required autocomplete="off" placeholder="Логин"></td>
        </tr>
        <tr>
            <td colspan="3"><div hidden id="login_error" class="error" ></div></td>
        </tr>
        <tr>
            <td><label for="login">Пароль: </login></td>
            <td><input type="password" name="password" id="password" required placeholder="Пароль" autocomplete="off"></td>
            <td><%= image_tag 'ce.svg', class: :pwdasset, 'data-subst' => (image_path 'oe.svg') %></td>
        </tr>
        <tr>
            <td colspan="3"><div hidden id="password_error" class="error" ></div></td>
        </tr>
        <tr>
            <td colspan="3"><input type="submit" value="Подтвердить"></td>
        </tr>
    </table>
</form>

lb12/app/app/views/users/regf.html.erb
<h1>Создание нового пользователя</h1>
<h3>Для начала работы необходимо зарегистрироваться или <a href=<%= login_path %>>войти</a> в уже существующий аккаунт</h3>

<form method="POST" action="/users/create" data-controller="create">
    <table>
        <tr>
            <td><label for="login">Логин: </login></td>
            <td colspan="2"><input type="text" name="login" id="login" required autocomplete="off" placeholder="Логин"></td>
        </tr>
        <tr>
            <td colspan="3"><div hidden id="login_error" class="error" ></div></td>
        </tr>
        <tr>
            <td><label for="login">Пароль: </login></td>
            <td><input type="password" name="password" id="password" required placeholder="Пароль" autocomplete="off"></td>
            <td><%= image_tag 'ce.svg', class: :pwdasset, 'data-subst' => (image_path 'oe.svg') %></td>
        </tr>
        <tr>
            <td colspan="3"><div hidden id="password_error" class="error" ></div></td>
        </tr>
        <tr>
            <td><label for="login">Подтвердите пароль: </login></td>
            <td><input type="password" name="passwordc" id="passwordc" placeholder="Подтвердите пароль" required autocomplete="off"></td>
            <td><%= image_tag 'ce.svg', class: :pwdasset, 'data-subst' => (image_path 'oe.svg') %></td>
        </tr>
        <tr>
            <td colspan="3"><div hidden id="passwordc_error" class="error" ></div></td>
        </tr>
        <tr>
            <td colspan="3"><input type="submit" value="Подтвердить"></td>
        </tr>
    </table>
</form>