rk2/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'input', to: 'head#input', as: 'input'
  get 'result', to: 'head#result', as: 'result'

  root 'head#input'
end

rk2/app/models/application_record.rb
# frozen_string_literal: true

# fi ojdfis j
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rk2/app/controllers/application_controller.rb
# frozen_string_literal: true

# fjidsofsj
class ApplicationController < ActionController::Base
end

rk2/app/controllers/head_controller.rb
# frozen_string_literal: true

# Head contrl
class HeadController < ApplicationController
  def input; end

  def result
    @err = nil
    @list = nil
    if params.key? :arr_z
      res = HeadHelper.make params[:arr_z]
      @list = params[:arr_z].split(', ')
      @err = res.last
      @list[res.first] = res[1] unless @err
    else
      @err = 'Вы не передали список'
    end
  end
end

rk2/app/helpers/application_helper.rb
# frozen_string_literal: true

# f djpso jf
module ApplicationHelper
end

rk2/app/helpers/head_helper.rb
# frozen_string_literal: true

# head helper
module HeadHelper
  def self.make(s_list)
    unless Regexp.new('^(-?\\d+(\\.\\d+)?,\\s)*(-?\\d+(\\.\\d+)?)$').match? s_list
      return [nil,
              'Неверный формат массива']
    end

    # @type [Array<Float>]
    list = s_list.split(', ').map(&:to_f)
    indk3 = list.find_index { |x| (x % 3).zero? }
    return [nil, nil, 'Нет элементов кратных 3'] unless indk3

    min = list.min
    indmin = list.find_index { |x| x == min }
    [indmin, indk3, nil]
  end
end

rk2/app/views/head/input.html.erb
<p>
    Дан массив чисел arr_z. Найти номер первого кратного 3 элемента и поместить этот номер на место минимального элемента.
</p>
<form action=<%= result_path %> method="get" data-controller="input">
        <table>
            <tr>
                <td><label for="arr_z">Введите массив чисел</label></td>
            </tr>
            <tr>
                <td><input type="text" name="arr_z" id="arr_z" required autocomplete="off"></td>
            </tr>
            <tr>
                <td><input type="submit" value="Обработать"></td>
            </tr>
            <tr>
                <td id="result"></td>
            </tr>
    </table>
</form>

rk2/app/views/head/result.html.erb
<% unless @err %>
    <p>Обработанный массив:</p>
    <div><%= @list.join(', ') %></div>
<% else %>
    <p>Возникла ошибка при обработке: <%= @err %></p>
<% end %>

<div>
<%= link_to "Назад ко вводу", input_path %>
</div>